version: '3.1'

networks:
  net1:

services:
  backend:
    image: aiohttp_python
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      net1:
        aliases:
          - backend
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      net1:
        aliases:
          - database
volumes:
  pg-data:
